export enum DoctorType {
  Cardiologist = 'cardiologist',
  Dermatologist = 'dermatologist',
  Neurologist = 'neurologist',
  Oncologist = 'oncologist',
  Pediatrician = 'pediatrician',
  Psychiatrist = 'psychiatrist',
  Radiologist = 'radiologist',
  Surgeon = 'surgeon',
  Anesthesiologist = 'anesthesiologist',
  Endocrinologist = 'endocrinologist',
  Gastroenterologist = 'gastroenterologist',
  Hematologist = 'hematologist',
  Immunologist = 'immunologist',
  Nephrologist = 'nephrologist',
  Obstetrician = 'obstetrician',
  Ophthalmologist = 'ophthalmologist',
  Orthopedist = 'orthopedist',
  Pathologist = 'pathologist',
  Pulmonologist = 'pulmonologist',
  Rheumatologist = 'rheumatologist',
  Other = 'other',
}
